FROM confluentinc/cp-kafka-connect-base:8.1.1

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

COPY build/confluentArchive/mongodb-kafka-connect-mongodb-2.0.1 /usr/share/confluent-hub-components/mongodb-kafka-connect
